### ISSUE TITLE
Promotion interrupted by login

### ISSUE THREAD

**Issue by andymelandy** [forcedotcom/devops-center-feedback#10]
**Describe the bug**
More of a UX tweak than a bug.  When promoting a work item to integration from dev, the promotion process is interrupted by the login prompt to the integration env, and I have to start the promotion process again.  Not a big deal, just a UX improvement.

**To Reproduce**
1. Given: logged in to DevOps Center, not logged in to Integration env
2. Promote a work item from dev to integration
3. Log in to integration env as prompted

**Expected behavior**
Once login to integration env is complete, I would expect the work item to be promoted to integration.  Instead I'm back to the screen where I need to promote the work item again.

**Screenshots**

**Additional context**

**Comment by kfidelak94** [comment]
In upcoming release, each individual user will only need to log into the environment once.
