### ISSUE TITLE
Ability to Customize Work Item

### ISSUE THREAD

**Issue by jremby** [forcedotcom/devops-center-feedback#142]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would like to be able to track additional data on the work item. Since work Item is a custom object I can create custom fields and customize the page layout but none of those changes are reflected on the Work Item when viewing in DevOps. It would also be nice to add relationships to other Objects like Cases or custom objects but again I don't think we have any ability to customize the layout unless I'm missing something

**Additional context**

**Comment by FabienTaillon** [comment]
This one may be linked to https://github.com/forcedotcom/devops-center-roadmap/issues/77

**Comment by kfidelak94** [comment]
Closing as DUP of https://github.com/forcedotcom/devops-center-roadmap/issues/77
