### ISSUE TITLE
Not all metadataitems is shown in "Add Components Manually"

### ISSUE THREAD

**Issue by johp-lb-dk** [forcedotcom/devops-center-feedback#145]
****Describe the bug****

Not able to select all medata-items manually , and add it to a workitem.

The documentation states:
"Commit Any Metadata Component Manually"

- Nothing is shown in standavalueset.
- Only some flows turns up.

**Reproduce**
Just try to add a standardvalueset to the work-item.

**Comment by RupertBarrow** [comment]
_"The Add Components Manually feature is currently operating against standard Metadata, not the decomposed source metadata format"_

Is this going to stay so indefinitely, or will we be able to select manually Metadata in src format (ie. separate CustomObject and CustomField, for example) ?
