### ISSUE TITLE
Work Items must be from the same stage to be promoted together.

### ISSUE THREAD

**Issue by monpilotagelec** [forcedotcom/devops-center-feedback#161]
Hello,

For the first time I have this error that blocks my deployment in Integration.

<img width="783" alt="image" src="https://user-images.githubusercontent.com/104131574/168542370-4dad7759-d908-44ef-a5c9-d0c3293cd238.png">

How can i solve the issue please?

**Comment by kfidelak94** [comment]
This will be fixed in the upcoming GA release, planned to release in December.

**Comment by HandreasC** [comment]
Hi, I'm experiencing the same mistake and don't quite understand why. 
I've merged it in GitHub after experiencing the same error message when trying to promote from inside DevOps Center 
![image](https://github.com/forcedotcom/devops-center-feedback/assets/149148375/500d1a53-29e3-40ba-8c86-86d301cf4a59)

**Comment by HandreasC** [comment]
Hi all, 

Salesforce Support debugged me with the following query : 
SELECT Id, sf_devops__Pipeline_Stage__r.Name,sf_devops__Work_Item__r.Name, sf_devops__Work_Item__c, sf_devops__Deployment_Result__r.sf_devops__Completion_Date__c, sf_devops__Deployment_Result__r.sf_devops__Deployment_Id__c, sf_devops__Merge_Result__r.sf_devops__Merge_Date__c,sf_devops__Merge_Result__r.sf_devops__Remote_Reference__c , sf_devops__status__r.sf_devops__status__c from sf_devops__Work_Item_Promote__c 

Then, had me delete the rows where sf_devops__Pipeline_Stage__r.Name = 'target Org' and sf_devops__status__r.sf_devops__status__c = 'Error'

**Comment by vernemi2** [comment]
> SELECT Id, sf_devops__Pipeline_Stage__r.Name,sf_devops__Work_Item__r.Name, sf_devops__Work_Item__c, sf_devops__Deployment_Result__r.sf_devops__Completion_Date__c, sf_devops__Deployment_Result__r.sf_devops__Deployment_Id__c, sf_devops__Merge_Result__r.sf_devops__Merge_Date__c,sf_devops__Merge_Result__r.sf_devops__Remote_Reference__c , sf_devops__status__r.sf_devops__status__c from sf_devops__Work_Item_Promote__c

On top of @HandreasC suggestion above, I had to delete the ones where `sf_devops__status__r.sf_devops__status__c` was empty. Then it worked again.
