### ISSUE TITLE
Receiving "Internal Server Error" when opening DevOps

### ISSUE THREAD

**Issue by qkershner** [forcedotcom/devops-center-feedback#164]
**Describe the bug**
Was recently allocated a new laptop (may be coincidental?) and now when I try to open DevOps, I receive the following error:
**Sorry to Interrupt
An internal server error has occurred
Error ID: 1949770054-142789 (470110760)**
![image](https://user-images.githubusercontent.com/8300797/170349282-9ef992e9-e237-4209-a8cd-d7473351a733.png)

**To Reproduce**
1. Open DevOps app in Production instance.

**Expected behavior**
Successfully open app.

**Screenshots**
An internal server error has occurred
Error ID: 1949770054-142789 (470110760)

**Additional context**

**Comment by qkershner** [comment]
@randallolson Checking for updates?  I've been unable to launch the the DevOps app for over a week, and I've verified the issue is not local to a specific machine.  Thank you.

**Comment by randallolson** [comment]
@qkershner - I have not been able to identify this problem yet.  When you say that you were able to verify the issue is not local to a specific machine, does that mean you have tried logging on using other machines?

**Comment by qkershner** [comment]
@randallolson Correct.  I've logged into the instance from multiple laptops and all result in the same error.

**Comment by qkershner** [comment]
Additional info:
1. I've verified no metadata changes appear to have occurred in Production that would suggest a change in configuration
2. DevOps App **will** open in sandboxes replicated from the production instance
3. Reviewed setup/configuration based on Documentation

**Comment by qkershner** [comment]
@randallolson Good morning, my apologies but checking for an update?  I've been 'dead in the water' for nearly 2 weeks.  Any status update or recommendations for resolution would be greatly appreciated.

**Comment by geomuck** [comment]
Thanks for your patience @qkershner !

Something is behaving strangely for sure. We're seeing this error in our logs:

```
 Subject: Compilation Failure
 		/sf_devops/projectSelectValidator/projectSelectValidator.js:25,4 : LWC1001: Unexpected compilation error: Unexpected token
```

What URL are you using when trying to open the DevOps Center? Are you trying to enter a specific project, or are you just trying to hit the root URI (/sf_devops/DevOpsCenter.app) ?

**Comment by qkershner** [comment]
I had 2 active projects.
Accessing directly?  I appended the URL to our instance URL, and received the same error.  I also opened one of the projects in a sandbox, and appended that project URL to our instance URL and same error.

**Comment by qkershner** [comment]
Similar error in Microsoft Edge.  And in Safari.

**Comment by geomuck** [comment]
Thank you. And since you have two Projects in this DevOps Center, the UI _was_ working at some point in the past, is that correct?

**Comment by geomuck** [comment]
One thing to try:

When you're comfortable doing so (for example, after business hours for your org), try going in to Setup, and then Apex Classes, then clicking Compile All Classes.

If that is successful, try loading the DevOps Center again?

If it's NOT successful, I'd like to know if at least the DevOps Center Apex classes were compiled successfully. You can create a custom list view on the Apex Classes page for "Invalid" classes, and it'll show you which classes need to be compiled/recompiled.

I'm definitely not sure about this theory, but I'm wondering if our LWC which references ProjectController.cls is failing because ProjectController.cls is invalid and needs recompiling...

Thanks!

**Comment by qkershner** [comment]
@geomuck You are correct, both projects were active and the app was functional.
I've run the Compile All Classes and everything appears Active and Valid (no errors).

**Comment by geomuck** [comment]
And the problem is persisting, I take it?

**Comment by qkershner** [comment]
Correct.  Just failed again after relaunch.

**Comment by qkershner** [comment]
@geomuck Not sure if it matters, but realized I left out that the tab opens as "Aura" when erroring out.
![image](https://user-images.githubusercontent.com/8300797/171958051-aa5e8b06-2308-4d71-a99e-91a51c0892a4.png)

**Comment by qkershner** [comment]
@geomuck I don't want to derail your analysis, but curious if it's time to try to uninstall/reinstall the managed package?

**Comment by kylewalke** [comment]
Hello @qkershner, based on George's input and what you've tried thus far I would only recommend trying to reinstall as a last resort because this removes all the metadata (which seems to be the problem) as well as the data (all of the records and data you've created in the project). If you are uncomfortable losing the data then we can keep trying other things, but if you are willing to start fresh, then this may be the next best option. I am investigating this as well in the meantime.

**Comment by qkershner** [comment]
We've been unable identify anything in our network infrastructure or hardware policies that would be causing the issue.  Following the SM22 refreshes, now none of the instances will connect to DevOps.  I recompiled one additional time and ran all tests. 
I'll be uninstalling and reinstalling the application this morning.

**Comment by fpardon-upeo** [comment]
Just wanna bump in here to say I had the same problem and got around it by disabling "Use Lightning Web Security for Lightning web components". 

I don't know why exactly, but the fact that the tab opened as Aura made me think of LWS...

**Comment by kylewalke** [comment]
@qkershner We've just released our Open Beta version of DevOps Center which should be available within the Setup Menu now. Would you mind trying to install the new version that way to see if you have any luck that way? Also, @fpardon-upeo that is great information for us to have so thank you for that! We will definitely do some testing with that as well.

**Comment by cverhaest** [comment]
Same issue for me. Disabling the "Use Lightning Web Security for Lightning web components" solve the issue but it should impact something else ...

**Comment by viktorvrabel** [comment]
Same here, unselecting "Use Lightning Web Security for Lightning web components" in Session settings worked.

**Comment by qkershner** [comment]
@cverhaest @viktorvrabel @kylewalke 
Turning off the Lightning Web Security setting resolved my issue as well.  I'll still plan to upgrade to the new Beta today to continue to work, but have to agree that the security setting seems to be an important issue to resolve?

**Comment by geomuck** [comment]
Thanks everyone. Yes, DevOps Center doesn't want any customers to have to _disable_ Lightning Web Security! We've narrowed in on the issue and should be able to resolve it within our package itself. Additionally, the DevOps Center team is working with the Lightning Web Security team internally to determine if there's anything that needs to be fixed/changed in the LWS feature as well (for other Partners who may encounter a similar issue).

Thanks for your patience. I'll keep this thread updated with status as we progress.

**Comment by geomuck** [comment]
This _should be_ fixed with [package 4.3.0](https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000HEChjSAH). However, at least one customer is reporting that they're still seeing the same bad behavior. If anyone else who is having this issue can confirm/deny that it's working after they've applied package 4.3.0, would you please reply here? Thanks very much!

**Comment by geomuck** [comment]
Update: it started working for that customer without any specific actions!

Still and all, if anyone else is still seeing this issue after 4.3.0, please do let us know. Thank you!

**Comment by fpardon-upeo** [comment]
Great! Do I get a T-shirt for finding what caused it? 😄

**Comment by geomuck** [comment]
@fpardon-upeo : DM me your mailing address and I'll see what I can do ;)

https://trailblazer.me/id/gmurnock
