### ISSUE TITLE
Trying to promote a Lightning Email Template fails when promoting

### ISSUE THREAD

**Issue by jremby** [forcedotcom/devops-center-feedback#165]
**Describe the bug**
Trying to promote a lightning email template to the next stage in the pipeline. When reviewing the error message it says:
"No source-backed components present in the package."

**Comment by randallolson** [comment]
@jremby - I am still working on this one.  I have not been able to replicate the issue yet, but I still have a couple things to try.

**Comment by randallolson** [comment]
@jremby - I have been able to confirm that this is a bug and we will fix it in a future release.

**Comment by jremby** [comment]
@randallolson do you have an estimate of when that might be? And in the meantime do you have recommendations on how to push items to production without breaking with version control etc?

**Comment by kfidelak94** [comment]
@jremby This will be fixed in the upcoming GA release, planned to release in December.
