### ISSUE TITLE
Modify Pipeline

### ISSUE THREAD

**Issue by jremby** [forcedotcom/devops-center-feedback#166]
I need to modify the pipeline of my project. Specifically the ability to change the Work item bundle setting for one of my stages. Is there no way to modify a pipeline once items have been promoted into the pipeline? Even if there are currently no items in that particular stage of the pipeline?

**Comment by randallolson** [comment]
@jremby - The pipeline cannot be deactivated (which would be required to make changes) once a work item as been promoted.  Even if it is not in the stage you would like to change.

**Comment by jremby** [comment]
@randallolson understood though very painful. Now I have to create a new project. Reassociate all orgs to the new project. Replicate all work items to the new project just because I can't modify the project pipeline. Is there any plans to change this?

**Comment by randallolson** [comment]
@jremby - We will be sure to look at it for changes.  Your question has been flagged and will be considered.

**Comment by jremby** [comment]
@randallolson Great. Thank you
