### ISSUE TITLE
Enhanced Domains Login

### ISSUE THREAD

**Issue by JodieM** [forcedotcom/devops-center-feedback#179]
Please allow login to Sandbox environments with Enhanced Domains

Allow the URL to be modified when creating an Environment

With Enhanced Domains logging in via test.salesforce.com does not seem to work. Creating a new Environment only goes to test.salesforce.com. I had to replace that part of the URL with my new enhanced domain to make it work.

**Comment by GilsonCanario** [comment]
Related to #210
