### ISSUE TITLE
Menu on Work Item to refresh sync from GitHub

### ISSUE THREAD

**Issue by RupertBarrow** [forcedotcom/devops-center-feedback#182]
**Is your feature request related to a problem? Please describe.**
When a developer makes a change on the Work Item branch in Github, this gets synced up automatically into DevOps Center.
However, there is a delay which is wuite long; a developer who is in a hurry and who plays the role of integration manager, might think that this feature is not working, or is too slow.

**Describe the solution you'd like**
It would be nice to have a menu item on the Work Item to force this sync/refresh.

**Additional context**

**Comment by GilsonCanario** [comment]
Related to #191
