### ISSUE TITLE
Can't pull source 

### ISSUE THREAD

**Issue by abhinavbajajsage** [forcedotcom/devops-center-feedback#19]
Trying to test the new functionality with DevOps Center 

-- Created a work item and connected to a Dev environment 
-- Created a new custom field in a Development environment 
-- Pulled changes
-- Received 45 items but not the custom field I created 

Am i doing something wrong?

**Comment by nihi-lb-dk** [comment]
Could you provide how to reset the source tracking counter in DevOps Center?
