### ISSUE TITLE
Cannot find standard fields

### ISSUE THREAD

**Issue by lbenetti** [forcedotcom/devops-center-feedback#194]
**Describe the bug**
I'm trying to commit the metadata and I found a limitation. In the scenario I used, I included new values in the Lead Status picklist, but I am not able to view this change using Pull Changes, and not even do this using the Add Components Manually feature. I know I need to commit the Lead object, the CustomField (Lead.Status) and the Standard Value Set (LeadStatus.standardValueSet), but I can't find any standard fields (all objects) and the stardard value set using Add Components Manually feature.
By the way, the .forceignore doesn't have any exclude rule.

**To Reproduce**
1. Go to Work Item
2. Click on Add Components Manually
3. Select the CustomField component type. 
4. Search for Lead.Status
5. The field doesn't appear

**Expected behavior**
Display the field to select

**Screenshots**
![image](https://user-images.githubusercontent.com/16101941/178076405-8fcd90a9-f21d-429d-be49-f00544092d23.png)

**Comment by lbenetti** [comment]
Hi @franciscoperezsammartino,

When pulling changes after modifying de picklist values, I can successfully add de StandardValueSet. Still, if I try to add the StandardValueSet manually, the behavior is the same as when trying to add standard CustomField.

Thank you for your attention.

**Comment by franciscoperezsammartino** [comment]
Hi @lbenetti ,
Can you please tell us the reason why you are trying to manually add the Lead.Status field and the Lead.object?
Does the commit or promotion fail if you add just the standard value set?

Thanks again!

**Comment by RupertBarrow** [comment]
Hi @GilsonCanario , please could you add a link to the duplicat issue # before closing ?  Thanks
