### ISSUE TITLE
I should be able to downsize the scope of a change request if promotion is failing

### ISSUE THREAD

**Issue by RupertBarrow** [forcedotcom/devops-center-feedback#199]
**Is your feature request related to a problem? Please describe.**
Promoting my change set is failing because of issues with deploying an experience bundle.
After a few tries at fixing it, I decide to give up : I will do the Experience Site configuration manually; I would like to remove the experience bundle from the scope of the change request.

This is not possible, I have to create a whole new Work Item !

**Describe the solution you'd like**
I would like to be able to change my mind and remove files from the scope of a change request.

**Additional context**

**Comment by GilsonCanario** [comment]
Related to #44
