### ISSUE TITLE
devops center page not loading

### ISSUE THREAD

**Issue by yosi-yaffe-alcd** [forcedotcom/devops-center-feedback#208]
**Describe the bug**
installed version 4.3.0
when redirected into [[mydomain]]/sf_devops/DevOpsCenter.app
i get a popup "Sorry to interrupt"
"This page has an error. You might just need to refresh it.
 [Cannot set properties of undefined (setting 'appState')]"

**To Reproduce**
1. after install finished step : https://help.salesforce.com/s/articleView?id=devops_center_assign_permsets.htm&type=5&language=en_US
2. open app luncher and press on "DevOps Center" connected app

**Expected behavior**
devops Center home page

**Screenshots**
![Capture](https://user-images.githubusercontent.com/26687468/186167263-666d6c44-9822-4c76-82c1-e4ab170cbf4c.PNG)

**Additional context**
didn't found anything in known issues / troubleshoot guide

**Comment by yosi-yaffe-alcd** [comment]
i also got this message based on the same steps to reproduce :
"Uncaught TypeError: Cannot read properties of undefined (reading '$getDef$')
throws at [[mydomain]]/auraFW/javascript/QPQi8lbYE8YujG6og6Dqgw/aura_proddebug.js:41342:83"

**Comment by itamargs** [comment]
It's the same as #181
Disabling "Debug Mode" for Lightning Components "solved" it for me

**Comment by GilsonCanario** [comment]
Hi @yosi-yaffe-alcd, could you confirm if you are still seeing this error after disabling debug mode?
