### ISSUE TITLE
Cannot promote to environment

### ISSUE THREAD

**Issue by johp-lb-dk** [forcedotcom/devops-center-feedback#211]
After Winter 2023 release on our sandboxes wer cannot promote workitems anymore

We get this error:
Did you log in to the correct environment?
We had a problem connecting to the environment, HF_DEV.

Unknown Authentication Error

Try again to connect to HF_DEV.

**Comment by geomuck** [comment]
Thanks for letting us know @johp-lb-dk ! Could you please reply with the organization ID where the DevOps Center is installed?

**Comment by johp-lb-dk** [comment]
Hi , solved it by using this naming in named credential:


Sandbox login | MyDomainName--SandboxName.sandbox.my.salesforce.com

**Comment by geomuck** [comment]
Exactly! We're working on step-by-step documentation to that effect, and should have it out very shortly. Glad you got yourself sorted out!
