### ISSUE TITLE
Unable to add dev environment to DevOps

### ISSUE THREAD

**Issue by noronmeridian** [forcedotcom/devops-center-feedback#219]
**Describe the bug**

I reinstalled DevOps and I Delete the DevOps center authentication providers.

- DevOps Center GitHub
- DevOps Center Prod
- DevOps Center Test

I attempt to manually recreate them which probably causes the issue that I can't add the dev environment to DevOps.

I was following the steps on the configuration guide, but when I try to add the dev environment and click on "Log In" button the system redirects to https://login.salesforce.com/ instead of https://test.salesforce.com/.

The issue occurs even if I don't check the "Used for development" box.

During configuration I mistakenly deleted the three Auth. Providers automatically created when enabling the DevOps Center.
So I manually created them again, without changing the default configuration.

I think this can cause the problem, but I don't know how to properly configure the Auth.Provider named DEVOPS_CENTER_TEST.

To Reproduce the issue - 

Delete the following Auth. Providers: DEVOPS_CENTER_GITHUB, DEVOPS_CENTER_PROD, DEVOPS_CENTER_TEST
Manually create them by providing only "Name" and "URL Suffix", leaving any other field blank.
Open the DevOps Center App, open a project then go to "Settings"
Click "Add"
Choose a Name for your environment, then select "Sandbox/Scratch Org"
Check the "Used for development" box (this step is optional, it doesn't work both ways)
Click on the "Log In" button
The system redirects to https://login.salesforce.com/ 

![image](https://user-images.githubusercontent.com/85349623/192798287-bfec8be7-ed55-410e-94fa-0ae8ef655e32.png)
Expected behavior
Be redirected to https://test.salesforce.com/
![image](https://user-images.githubusercontent.com/85349623/192800151-bb748b1f-d287-42df-94df-4a20fa4907aa.png)

**Comment by ekapner** [comment]
Per the docs, you should open a GitHub issue if you delete the auth providers.
https://help.salesforce.com/s/articleView?id=sf.devops_center_uninstall_auth_providers.htm

**Comment by kylewalke** [comment]
Hi @noronmeridian, we appreciate you reporting this bug to us! Are you able to alter the url in the "Devops Center Test" url to replace https://login.salesforce.com with https://test.salesforce.com/ like below? 
![Screen Shot 2022-09-16 at 12 55 05 PM](https://user-images.githubusercontent.com/13628780/192928846-98dc86d3-6bf8-4a5d-9441-9412fcb9196d.png)

**Comment by kylewalke** [comment]
@noronmeridian After more investigation, I've discovered that there are some steps we need to take to re-enable your org for DevOps Center specifically. We are working on it and will notify you here when your org is ready to reinstall DevOps Center. Please hang tight and thank you for your patience!

**Comment by noronmeridian** [comment]
Kyle, I also open a ticket with Salesforce.
Yesterday they contacted me and ask me to delete “DevOps Center Test<javascript:srcUp(%27%2F0SO4U0000004Dfz%3Fisdtp%3Dp1%27);>” provider, and they will create it.
today I verified that they recreated DevOps Center Test<javascript:srcUp(%27%2F0SO4U0000004Dfz%3Fisdtp%3Dp1%27);>.

And now I can add Dev environment to Devops Center.

For now, its look like it’s working.

You can close the case

Nissim Oron
Salesforce Administrator
O: (646) 502-3441
M: (917) 742-9392
***@***.******@***.***>

**Comment by kylewalke** [comment]
Oh, great! Glad this is resolved for you. Thank you for lettings us know!
