### ISSUE TITLE
Metadata gets pulled with an old API version

### ISSUE THREAD

**Issue by pklosNxs** [forcedotcom/devops-center-feedback#221]
**Describe the bug**
Flows that are pulled via DevOps Center do not have an XML element "regionContainerType". Therefore, they cannot be deployed when pulled through the DevOps Center into a project running on >=API V55.
Probably DevOps Center is using Metadata API V54 to pull the changes because that element was introduced in V55. 

**To Reproduce**
1. Create a new Screen-Flow
2. Add a new screen 
3. Add a section to the screen
4. Save the flow, running API V55 or V56
5. Commit the flow via DevOps Center into a sfdx project running API V55
6. Review the metadata or try to deploy the flow -> regionContainerType is missing

**Expected behavior**
It is expected that metadata will be pulled in the api version that is currently running on production and thus can also be used for further deployments against production

**Screenshots**
Line 33 - Line 53
![image](https://user-images.githubusercontent.com/78013661/193993368-51a08fe4-bf42-442a-9b4d-f8072e8f44c9.png)

**Comment by kfidelak94** [comment]
@pklosNxs - yes, this is a bug we're aware of where we were hard-coded to v53 of the API.  This has been fixed in our upcoming GA release (Dec). Sorry for the trouble.

**Comment by Schuchie** [comment]
@kfidelak94 which API-Version do you use then (in the dec release), the latest or the used one in the sfdx-project.json?

**Comment by kfidelak94** [comment]
@Schuchie If a version is specified in the sfdx-project.json, that will take precedence.  Otherwise it will use the latest API version.

**Comment by Schuchie** [comment]
@kfidelak94 perfect!

**Comment by TelmoKz** [comment]
@kfidelak94  There is any workaround meanwhile?
