### ISSUE TITLE
Cannot see details of test failures

### ISSUE THREAD

**Issue by jawills** [forcedotcom/devops-center-feedback#225]
**Describe the bug**
In a deployment error details, the test failure count is shown, but not any details about the tests that failed
**To Reproduce**
1. Create a Work Item Bundle that will not pass tests in production
2. Push bundle to production
4. Click on 'View Details' in the promotion failed section
3. Click on View Errors 
...

**Expected behavior**
When the errors are given for a work item bundle, a user should see the names of the tests that failed, along with the failure reason

**Comment by geomuck** [comment]
For sure, and thanks for your comment! The test failure output can get REALLY lengthy, and we made the decision to simply specify that there were test failures, and how many.

We encourage users to go look at the Apex test results in the org-in-question, and one can open that org easily from the DevOps Center.

That said, a reasonable enhancement might be for the DevOps Center to provide a link to the detailed test failures in the org, within the error message? We'd love to hear your input as well @jawills !

**Comment by jawills** [comment]
I think that a link to the test output is more than sufficient. I would not want to debug test classes in the small modal.
