### ISSUE TITLE
After upgrade to version 5.3.0 can not configure new project. 

### ISSUE THREAD

**Issue by epanor** [forcedotcom/devops-center-feedback#242]
**Describe the bug**
After upgrade to version 5.3.0 can not configure new project. 

**To Reproduce**
1. Create new project with new or existing GitHub repository
2. Press on "Click to Connect" under release environment
3. In popup window choose "Production Org" and press "Log in"
4. Error message appears - "There was an error. Please reload the page or contact your system administrator if the problem persists."

**Screenshots**
![image](https://user-images.githubusercontent.com/117648234/207813660-42f23a8f-8542-4c06-b080-6d717a822408.png)
![tempsnip](https://user-images.githubusercontent.com/117648234/207814242-a10b4b89-7d19-4664-8c5a-9c85439cda90.png)

**Additional context**
OrgId : 00D8d000007YQN2

**Comment by geomuck** [comment]
We've resolved this. There was some as-yet-unknown issue with the user's browsing environment. Switching to mobile didn't show this same issue.
