### ISSUE TITLE
Promoting workitems from sandbox to production is failing for DigitalExperienceBundle

### ISSUE THREAD

**Issue by nalinisriv** [forcedotcom/devops-center-feedback#253]
**Describe the bug**
When a experience site is created in setup and changes are pulled into devops center with metadata types DigitalExperienceBundle, DigitalExperience and DigitalExperienceConfig promotion to production fails with errors.

`newdev1site1 of Type DigitalExperienceConfig failed to deploy due to One piece of content with the contentType sfdc_cms__appPage is required to create the experience space site/newdev1site1. newdev1site of Type Network failed to deploy due to In field: PicassoSite - no SiteDotCom named newdev1site1 found newdev1site of Type CustomSite failed to deploy due to In field: Name - no Network named newdev1site found`

The support for DigitalExperienceBundle was added through https://github.com/forcedotcom/source-deploy-retrieve/releases/tag/6.8.0 which does not seems to be working.

**To Reproduce**
1. In sandbox setup, Enable Digital Experiences and create a new site. Follow - https://confluence.internal.salesforce.com/pages/viewpage.action?spaceKey=CMSCM&title=CMS+App+Setup
2. In Devops center, create a workitem and pull the changes for DigitalExperienceBundle, Network, CustomSite, DigitalExperienceConfig. 
Create Review, Select Ready to Promote.
3. In pipeline, Promote the changes in workitem. Promotion fails with error given above.

...

**Expected behavior**
Site should get deployed to production.

**Screenshots**
![image](https://user-images.githubusercontent.com/123750887/220251906-f93afce2-86c7-4626-8b88-1b974f6035d1.png)

**Additional context**
Support for DigitalExperienceBundle was added through https://github.com/forcedotcom/source-deploy-retrieve/releases/tag/6.8.0
The same site when deployed through sfdx is successful. Only with devops center promotion fails.

**Comment by nalinisriv** [comment]
Updated Additional context.

**Comment by nalinisriv** [comment]
Investigation was logged and it's closed on GUS. https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001LiyyOYAR/view

**Comment by sdavis-stack** [comment]
@nalinisriv Does this actually work now in DevOps Center?
