### ISSUE TITLE
Committing to Work Item and Promoting Work Item's Both Stalling

### ISSUE THREAD

**Issue by watsonps** [forcedotcom/devops-center-feedback#265]
**Describe the bug**
When Committing changes to a work item, just as I have done 100s of times the status message freezes on "Committing" with the subtext "Pushing". The item in Github is committing successfully, but DevOps Center is getting stuck.

This is also happening when trying to promote existing work items that have been approved. It gets stuck on "Promoting".

**To Reproduce**
1. Create New Work Item
2. Add Some Changes 
3. Commit said changes

**Expected behavior**
Normally in the past it would quickly and easily complete the commit / promote and I could continue working.

**Screenshots**
![image](https://github.com/forcedotcom/devops-center-feedback/assets/128385384/e568a857-1c97-4ac9-ac09-c8ae7f618e7c)

**Additional context**
This is preventing me from continuing with work. I tried creating an entirely new project to see if that was the issue to no avail.

**Comment by watsonps** [comment]
> I have been experiencing the same all day long...

Thats comforting to hear! It may not just be me then! The workarounds listed here:

https://help.salesforce.com/s/articleView?id=sf.devops_center_promotion_stalled_succeeded.htm&type=5
https://help.salesforce.com/s/articleView?id=sf.devops_center_commit_stalled.htm&type=5

Do work, but my is this tedious and time consuming. Possibly an issue with Summer 23 release?

**Comment by SERgroupGithub** [comment]
I have the same problem in the last few weeks. The workarounds from salesforce help helped me to get the commit in a completed state but the promotion stalled too and i cant get them working correctly that the changed are correctly deployed to the next stage. 
I have also setup the devops project completly fresh but i get this issue again. Think this is since the Summer 23 release

**Comment by aojedo-signify** [comment]
I got into an endless loop with Salesforce Support:
- Here's a workaround for your stalled commits
- I'm not going to fix EVERY commit
- Let me check with the DevOps Team: oh they said you have this workaround
- ...

**Comment by watsonps** [comment]
Update: After working with Salesforce support they mentioned the issue is related to total number of lines being committed, but I noticed that really isn't the case in my instance since even a one single line change commit causes the same problem.

They mentioned they are away of the issue and that we can expect a fix in the next 2-3 weeks.

**Comment by rgarcia-accelerize360** [comment]
We encountered this issue too today. Any workarounds please? Did they commit to fix the issue?

**Comment by watsonps** [comment]
Just a small update, still experiencing this problem, getting quite frustrated. @rgarcia-accelerize360 the workaround I posted earlier still works but it takes so much extra time.

I escalated and restarted my case with Salesforce, we shall see if they have any updates.

**Comment by watsonps** [comment]
I actually got this issue resolved with Salesforce! They discovered my Permission Sets related to DevOps Center had changed when I updated DevOps Center so I had to reassign the DevOps Center and DevOps Center release Permission Sets and my commits and promotions are no longer stalling!

**Comment by dinhphieu** [comment]
@watsonps that was the reason for me too! Thanks a lot for sharing the solution
