### ISSUE TITLE
Unable to commit changes: A security setting is preventing us from completing this operation.

### ISSUE THREAD

**Issue by jacshe** [forcedotcom/devops-center-feedback#270]
**Describe the bug**
I'm unable to commit changes to github and when pressing commit I get the error message 

Commit Failed: A security setting is preventing us from completing this operation. See Troubleshoot DevOps Center Configuration for details.

A new branch is created in the github repository so the authorisations seems to work. The repo is owned by an organisation but the "Salesforce Integration Application" have been authorised access to the organisation.

Are there any way to get more details about the error message?

**To Reproduce**
1. Pull changes
2. Select changes
3. Commit changes

**Expected behavior**
 The changes to be commited to the github and work item.

**Screenshots**
<img width="846" alt="image" src="https://github.com/forcedotcom/devops-center-feedback/assets/3329395/ada39880-8fe0-490e-bab9-feebb3d4efa3">

**Comment by grigorian** [comment]
We had this issue when we moved our developers away from 'System Administrator' profiles in Production.  After some investigation (the error message is not the best!) we found this was related to the fact that we set the 'Session Security Level Required at Login' to 'High Assurance'.  Changing this setting back to '--None--' resolved the issue.

**Comment by jacshe** [comment]
Thanks, this solved the issue!
