### ISSUE TITLE
Getting sf_devops:Too many callouts: 101 when promoting work item bundle

### ISSUE THREAD

**Issue by bbarlow-knauf** [forcedotcom/devops-center-feedback#273]
**Describe the bug**
I have a work item bundle with 4 items in it. One of the items has been merged from two work items because they shared metadata.

**To Reproduce**
1. Promote items into the pipeline, have two items that have updated the same metadata.
2. Promote the items from the first stage of the pipeline to the next ensuring that the items with the same metadata are promoted at the same time and DevOps Center askes to merge the work items.
3. Promote items into the second to last stage where they are combined into a work item bundle
4. Attempt to promote the work item bundle to the final stage. Error should occur.

**Expected behavior**
The promote work item bundle screen should be displayed asking for a version name of the bundle, select what metadata is deployed and what test level to run.

**Screenshots**
![image](https://github.com/forcedotcom/devops-center-feedback/assets/128617654/abdf9991-5098-4008-873b-da395e3db064)

**Additional context**
This is preventing bug fixes from being deployed to my production environment that are scheduled to go live today.

**Comment by bbarlow-knauf** [comment]
Completed the merge in GitHub and DevOps center recognized the merge and prompted me to complete the promotion.

**Comment by peterSalytics86** [comment]
Thanks for the workaround @bbarlow-knauf ! But this shouldn't be happening in the first place... Salesforce should look into this...
