### ISSUE TITLE
Promotion Failed due to "CustomObjectTranslation insufficient access rights on cross-reference id" and cannot fix (Remove file from commit)

### ISSUE THREAD

**Issue by jotraverso** [forcedotcom/devops-center-feedback#45]
**Describe the bug**
I got a WI which includes the Account-en_US Object Translation, and got a _"CustomObjectTranslation insufficient access rights on cross-reference id"_ error when deploying

It's ok, it's failing, then I try to remove the field from the WI git branch, and then got this error when promoting
`Expected metadata file with '-meta.xml' extension at path: /tmp/doce-9ewLn9/force-app/main/default/objectTranslations/Account-en_US/Account-en_US.objectTranslation-meta.xml
`
**To Reproduce**
1. Create a Work Item
2. Make some changes in the Dev Org, as create new Account Fields
3. Pull changes from the Dev Org to the Work Item, ensure you have the Account-en_US file on the Work Item
4. Try to promote, you will get the _"insufficient access rights on cross-reference id"_ error
5. Go to the Github branch for the Work Item
6. Remove the Account-en_US file from the git branch
7. Try to promote again, you will get the _"Expected metadata file with '-meta.xml' extension at path"_ error

**Expected behavior**
Whish the step 7 not failing or any way to remove or reset files on the WorkItem.

**Screenshots**
![image](https://user-images.githubusercontent.com/1578954/120798055-17542700-c53d-11eb-94c3-35751202aa1d.png)

![image](https://user-images.githubusercontent.com/1578954/120798393-95183280-c53d-11eb-991c-4dd080040a03.png)

**Additional context**
N/A

**Comment by jonny-harte** [comment]
@kfidelak94 I can't see a Modified Remote Changes field on the Change Submission object. Has the data model changed?

I can see related lists to Remote Changes & Submit Components. Remote Changes only has records for commits done through DevOps Center, not external commits.

Do I need to delete the Submit Component and Remote Change (if present)?

Is it also safe to delete the whole Change Submission if the commit has been removed in Git?

**Comment by oleg-mastriukov** [comment]
Yes, the field was deprecated, so I believe completely deleting records is the way.
![image](https://github.com/forcedotcom/devops-center-feedback/assets/46223141/fa163196-b9d0-4619-b0f9-fa0d8d1e5490)
