### ISSUE TITLE
Can't select Dev Environment from Work Item (Environment is DE org without source tracking enabled)

### ISSUE THREAD

**Issue by kondasx1** [forcedotcom/devops-center-feedback#57]
We are unable to select the "Development Environment" in the work item

1. Open WI-000000
2. The select dropdown is blank in the Development Environment field

**Expected behavior**
Expected to select the environment from the dropdown

**Screenshots**
![image](https://user-images.githubusercontent.com/60946300/122105360-4e98c280-cdde-11eb-969e-b8d81bd8f4d1.png)

**Additional context**
Please note that we have used Developer edition as our dev environment for pilot. We are not sure if that is what is causing the issue.

**Comment by kfidelak94** [comment]
In upcoming release, DevOps Center will not allow you to add an environment as a Development Environment if it doesn't have Source Tracking enabled.
