### ISSUE TITLE
New Project - cannot find existing repo (Github organization)

### ISSUE THREAD

**Issue by akateguz** [forcedotcom/devops-center-feedback#58]
**Describe the bug**
When I enter the URL to my repo, message displays "Hmm, we can’t find the thehartford/salesforce-devops-pilot repository."

**To Reproduce**
1. Select New Project
2. Choose "Use an existing repository for my project."
3. Copy repo link from GitHub 

**Expected behavior**
Find & connect to GitHub Repo: thehartford/salesforce-devops-pilot

**Screenshots**
![Snag_4697e35](https://user-images.githubusercontent.com/85622189/124032983-543dfd00-d9c7-11eb-9773-8748f46fcb3d.png)

**Additional context**
I am Admin of GitHub Repo: thehartford/salesforce-devops-pilot
visibility is private
"sfdx-project.json" file was created per instructions

**Comment by GilsonCanario** [comment]
This have been added to the [docs](https://help.salesforce.com/s/articleView?id=sf.devops_center_org_owns_github_repo.htm&type=5).
