### ISSUE TITLE
Promotion Stalled

### ISSUE THREAD

**Issue by SAxcell** [forcedotcom/devops-center-feedback#70]
**Describe the bug**
Trying to promote changes from sandbox to production we got an error "Promotion Stalled".  When I click for details it says promotion failed, no further details.  When I try to promote again it says internal data model error, contact the system admin.  

**To Reproduce**
1. Not sure how to stall the promotion.  We tried to promote but after a couple of hours nothing was happening.  This happened when we tried to again
2. Promote bundle from Validation to Production
3. Error says There was a internal data model error.
Please reload the page or contact your system administrator if the problem persists.
...

**Expected behavior**
Bundle promoted from Validation to Production

**Screenshots**

![image](https://user-images.githubusercontent.com/84103048/125368558-6feebf00-e348-11eb-8f7f-275e73a7b7d4.png)

![image](https://user-images.githubusercontent.com/84103048/125368599-914fab00-e348-11eb-9cf1-9177a4ecc376.png)

![image](https://user-images.githubusercontent.com/84103048/125368615-99a7e600-e348-11eb-8afc-8f595dde3b15.png)

**Additional context**
@srihithacherukuri14 and I both have the same issue trying to promote this bundle.

**Comment by GilsonCanario** [comment]
We believe this has been resolved. If the error shows up again, we will address it in another ticket.
